/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Conexao.ConexaoBDH;
import Dao.PedidoDAO;
import com.mycompany.planetas.Cliente;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Positivo
 */
public class Telapedido extends javax.swing.JFrame {
     Cliente pedido = new Cliente();
     DecimalFormat df = new DecimalFormat("0.00");


      
    /**
     * Creates new form Telapedido
     */
    public Telapedido(String cliente, int mesa) {
        initComponents();
        pedido.cliente=cliente;
        pedido.mesa=mesa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formadepagar = new javax.swing.ButtonGroup();
        panelsupremo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nmlogo = new javax.swing.JLabel();
        cardapio = new javax.swing.JButton();
        Realizarpedido = new javax.swing.JButton();
        Fecharconta = new javax.swing.JButton();
        txtquantidade = new javax.swing.JLabel();
        qntd = new javax.swing.JTextField();
        lbcodigo = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        cre = new javax.swing.JRadioButton();
        deb = new javax.swing.JRadioButton();
        money = new javax.swing.JRadioButton();
        pix = new javax.swing.JRadioButton();
        parcelar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Sairvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelsupremo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        nmlogo.setFont(new java.awt.Font("Segoe Script", 3, 17)); // NOI18N
        nmlogo.setText("Planeta dos Sabores");

        cardapio.setBackground(new java.awt.Color(204, 204, 204));
        cardapio.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        cardapio.setText("Cardápio");
        cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardapioActionPerformed(evt);
            }
        });

        Realizarpedido.setBackground(new java.awt.Color(153, 255, 153));
        Realizarpedido.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Realizarpedido.setText("Pedir");
        Realizarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarpedidoActionPerformed(evt);
            }
        });

        Fecharconta.setBackground(new java.awt.Color(255, 204, 204));
        Fecharconta.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        Fecharconta.setText("Fechar Conta");
        Fecharconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharcontaActionPerformed(evt);
            }
        });

        txtquantidade.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        txtquantidade.setText("Quantidade");

        lbcodigo.setFont(new java.awt.Font("Segoe Script", 0, 12)); // NOI18N
        lbcodigo.setText("Codigo Produto");

        formadepagar.add(cre);
        cre.setText("Crédito");

        formadepagar.add(deb);
        deb.setText("Débito");

        formadepagar.add(money);
        money.setText("Dinheiro");
        money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyActionPerformed(evt);
            }
        });

        formadepagar.add(pix);
        pix.setText("Pix");

        parcelar.setText("Parcelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nmlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parcelar)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(money)
                            .addComponent(pix)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cardapio)
                                .addGap(21, 21, 21)
                                .addComponent(Realizarpedido)
                                .addGap(18, 18, 18)
                                .addComponent(Fecharconta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cre)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qntd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbcodigo))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nmlogo)
                .addGap(23, 23, 23)
                .addComponent(txtquantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cre)
                    .addComponent(qntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deb)
                    .addComponent(parcelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(money)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pix)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cardapio)
                            .addComponent(Realizarpedido)
                            .addComponent(Fecharconta))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbcodigo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Tela de Pedidos");

        Sairvoltar.setBackground(new java.awt.Color(255, 51, 51));
        Sairvoltar.setText("X");
        Sairvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelsupremoLayout = new javax.swing.GroupLayout(panelsupremo);
        panelsupremo.setLayout(panelsupremoLayout);
        panelsupremoLayout.setHorizontalGroup(
            panelsupremoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelsupremoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sairvoltar))
        );
        panelsupremoLayout.setVerticalGroup(
            panelsupremoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsupremoLayout.createSequentialGroup()
                .addGroup(panelsupremoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Sairvoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsupremo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelsupremo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyActionPerformed

    private void RealizarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarpedidoActionPerformed
        try{
        pedido.a = Integer.parseInt(codigo.getText()); 
        pedido.qnt = Integer.parseInt(qntd.getText()); 
        
        if(parcelar.isSelected()){
        pedido.parcelar=parcelar.getText();
        pedido.s=1;
        }
        if (pix.isSelected()){
            pedido.formapagar = pix.getText();
               pedido.b=0;
        } else if (deb.isSelected()) {
            pedido.formapagar = deb.getText();
               pedido.b=0;
        } else if (cre.isSelected()) {
            pedido.formapagar = cre.getText();
            pedido.b=1;
        } else if (money.isSelected()) {
            pedido.formapagar = money.getText();
               pedido.b=0;
        }

        if (pedido.a > 0 && pedido.qnt > 0 && pedido.formapagar != null) {
            pedido.x+=pedido.qnt;
            PedidoDAO pedidoDAO = new PedidoDAO();
            Cliente pedidoDoBanco = pedidoDAO.buscarPedidoPorId(pedido.a);

            if (pedidoDoBanco != null) {
                
                for(pedido.p=0;pedido.p<pedido.qnt;pedido.p++){
                    pedido.svalor += pedidoDoBanco.svalor;
                    pedido.preco=pedidoDoBanco.svalor;
                    }
                if (pedido.p == pedido.qnt) {
                        JOptionPane.showMessageDialog(null, "Cliente= " + pedido.cliente
                                + "\nMesa= " + pedido.mesa 
                                + "\nPedido = " + pedidoDoBanco.produto 
                                + "\nQuantidade = " + pedido.qnt 
                                + "\n Valor por item= " + df.format(pedido.preco)
                                + "\n Valor total= " + df.format(pedido.svalor)); 
            
                 ConexaoBDH.inserirHistorico(pedido.cliente, pedido.mesa, pedidoDoBanco.produto, pedido.qnt,pedido.preco, pedido.svalor,pedido.formapagar);
                                }


            } else {
                JOptionPane.showMessageDialog(null, " Codigo invalido");
            }
        }  else if( pedido.formapagar == null){
        JOptionPane.showMessageDialog(null, "\n Forma de Pagamento NAO INFORMADO!");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Erro de formato. Certifique-se de que a quantidade é um número válido.");
    }
    }//GEN-LAST:event_RealizarpedidoActionPerformed

    private void cardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapioActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }//GEN-LAST:event_cardapioActionPerformed

    private void SairvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairvoltarActionPerformed
        // TODO add your handling code here:
       if(pedido.svalor>0){
       JOptionPane.showMessageDialog(null,"A CONTA NÃO FOI PAGA!");
       }else{  
               setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telainicio().setVisible(true);
            }
        });
       }
    }//GEN-LAST:event_SairvoltarActionPerformed

    private void FecharcontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharcontaActionPerformed
        // TODO add your handling code here:
        pedido.d=pedido.s+pedido.b;
        if(pedido.svalor>0 && pedido.d==2){            
        if(pedido.svalor<50){
        JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Valor Insuficiente para parcelar");    
          pedido.svalor=0;
        }
        else if(pedido.svalor>50 && pedido.svalor<=80){
        JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Valor pode ser parcelado em ate 2x de: "+df.format(pedido.svalor/2));    
          pedido.svalor=0;
        }
        else if(pedido.svalor>80 && pedido.svalor<=150){
        JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Valor pode ser parcelado em ate 3x de: "+df.format(pedido.svalor/3));    
          pedido.svalor=0;
        }
        else if(pedido.svalor>150){
        JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Valor pode ser parcelado em ate 5x de: "+df.format(pedido.svalor/5));    
          pedido.svalor=0;
        }
         } 
       else if(pedido.svalor>0 && pedido.b!=2){
        
           if(pedido.formapagar=="Dinheiro"){
       String pago=JOptionPane.showInputDialog("Informe a quantia para pagamento\n Valor tem que ser maior ou igual a: "+df.format(pedido.svalor));
       pedido.vpago=Double.parseDouble(pago);
       while(pedido.vpago<pedido.svalor)   {
       
       pago=JOptionPane.showInputDialog("Informe a quantia para pagamento\n Valor tem que ser maior ou igual a: "+pedido.svalor);
       pedido.vpago=Double.parseDouble(pago);
       
                    }
       
       pedido.troco=pedido.vpago-pedido.svalor;
      JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Forma de Pagamento= "+pedido.formapagar+"\n Valor pago= "+df.format(pedido.vpago)+"\n Troco= "+df.format(pedido.troco));
       }
       
      else{
            JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Forma de Pagamento= "+pedido.formapagar);
            pedido.svalor=0;
           
         }
           
           
        }
        else{
           
            JOptionPane.showMessageDialog(null,"Houve um erro inesperado!\n"+pedido.svalor+"\n");
        }       
        setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telainicio().setVisible(true);
            }
        });
    }//GEN-LAST:event_FecharcontaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telapedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telapedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telapedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telapedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telapedido().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fecharconta;
    private javax.swing.JButton Realizarpedido;
    private javax.swing.JButton Sairvoltar;
    private javax.swing.JButton cardapio;
    private javax.swing.JTextField codigo;
    private javax.swing.JRadioButton cre;
    private javax.swing.JRadioButton deb;
    private javax.swing.ButtonGroup formadepagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JRadioButton money;
    private javax.swing.JLabel nmlogo;
    private javax.swing.JPanel panelsupremo;
    private javax.swing.JRadioButton parcelar;
    private javax.swing.JRadioButton pix;
    private javax.swing.JTextField qntd;
    private javax.swing.JLabel txtquantidade;
    // End of variables declaration//GEN-END:variables
}

