/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Dao.EncontrarFuncionarioDAO;
import com.mycompany.planetas.Funcionarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Positivo
 */
public class TelaLogin extends javax.swing.JFrame {
       Funcionarios colaborador= new Funcionarios();
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1superior = new javax.swing.JPanel();
        jPanelsecundario = new javax.swing.JPanel();
        Nmusuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuarionome = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        Panielbranco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1superior.setBackground(new java.awt.Color(153, 153, 153));

        jPanelsecundario.setBackground(new java.awt.Color(153, 255, 255));

        Nmusuario.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        Nmusuario.setText("Cpf");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 14)); // NOI18N
        jLabel3.setText("Senha");

        usuarionome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarionomeActionPerformed(evt);
            }
        });

        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelsecundarioLayout = new javax.swing.GroupLayout(jPanelsecundario);
        jPanelsecundario.setLayout(jPanelsecundarioLayout);
        jPanelsecundarioLayout.setHorizontalGroup(
            jPanelsecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsecundarioLayout.createSequentialGroup()
                .addGroup(jPanelsecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelsecundarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelsecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuarionome)
                            .addComponent(senha)))
                    .addGroup(jPanelsecundarioLayout.createSequentialGroup()
                        .addGroup(jPanelsecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelsecundarioLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelsecundarioLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(Nmusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsecundarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Entrar)
                .addGap(26, 26, 26))
        );
        jPanelsecundarioLayout.setVerticalGroup(
            jPanelsecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsecundarioLayout.createSequentialGroup()
                .addComponent(Nmusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarionome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Entrar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        Panielbranco.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 16)); // NOI18N
        jLabel1.setText("Restaurante");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 16)); // NOI18N
        jLabel2.setText("Planeta dos Sabores");

        voltar.setBackground(new java.awt.Color(255, 102, 102));
        voltar.setText("X");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanielbrancoLayout = new javax.swing.GroupLayout(Panielbranco);
        Panielbranco.setLayout(PanielbrancoLayout);
        PanielbrancoLayout.setHorizontalGroup(
            PanielbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanielbrancoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanielbrancoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(voltar))
        );
        PanielbrancoLayout.setVerticalGroup(
            PanielbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanielbrancoLayout.createSequentialGroup()
                .addGroup(PanielbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        login.setFont(new java.awt.Font("Segoe Script", 3, 16)); // NOI18N
        login.setForeground(new java.awt.Color(204, 255, 255));
        login.setText(" Login");

        javax.swing.GroupLayout jPanel1superiorLayout = new javax.swing.GroupLayout(jPanel1superior);
        jPanel1superior.setLayout(jPanel1superiorLayout);
        jPanel1superiorLayout.setHorizontalGroup(
            jPanel1superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panielbranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1superiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1superiorLayout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1superiorLayout.createSequentialGroup()
                        .addComponent(jPanelsecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel1superiorLayout.setVerticalGroup(
            jPanel1superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panielbranco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelsecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1superior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarionomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarionomeActionPerformed
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_usuarionomeActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
       colaborador.cpf=usuarionome.getText();
       char[] senhaChars = senha.getPassword();
        String senhaString = new String(senhaChars);
        colaborador.registro = Integer.parseInt(senhaString);
      
       if(colaborador.registro>0 && (!"".equals(colaborador.cpf))){
       
             try {
            EncontrarFuncionarioDAO funcionarioDAO = new EncontrarFuncionarioDAO();
            Funcionarios funcionario = funcionarioDAO.buscarFuncionarioPorCpf(colaborador.cpf, colaborador.registro);

            if (funcionario != null) {

                JOptionPane.showMessageDialog(null, "Funcionário autenticado com sucesso!\n\nNome: " + funcionario.nome + "\nNível de acesso: " + funcionario.nivel);
          if(funcionario.nivel==2){
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                new Telahistorico().setVisible(true);
                    }
                        });
                }
         else if(funcionario.nivel==1){
                 java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                new TelaGerente().setVisible(true);
                }
                    });
                }
        else if(funcionario.nivel==0){
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                new TelaDono().setVisible(true);
                }
                    });
                }
        else{
        JOptionPane.showMessageDialog(null, "Nivel de acesso invalido ");
        }
               
               
            } else {
                JOptionPane.showInputDialog("Credenciais inválidas. Funcionário não encontrado.");
               
            }
        } catch (Exception e) {
            e.printStackTrace(); 
        }
       }
       
       
       
       
    }//GEN-LAST:event_EntrarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telainicio().setVisible(true);
            }
        });
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel Nmusuario;
    private javax.swing.JPanel Panielbranco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1superior;
    private javax.swing.JPanel jPanelsecundario;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuarionome;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
