/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.psabor;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Positivo
 */
public class Tela2 extends javax.swing.JFrame {
  Restaurante pedido= new Restaurante();
  DecimalFormat df = new DecimalFormat("0.00");
  DefaultComboBoxModel modelo;
  
   /** private String cliente;
    private Restaurante mesa;

    Tela2(String cliente, Restaurante mesa) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Métodos de configuração (setters)
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    public void setPedido(Restaurante mesa) {
        this.pedido = mesa;
    }
   
     * Creates new form Tela2
     */
    public Tela2(String cliente, int mesa) {
        pedido.cliente=cliente;
        pedido.mesa= mesa;
        initComponents();
        modelo= (DefaultComboBoxModel )BoxCodigo.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Telageral = new javax.swing.JPanel();
        cardapio = new javax.swing.JButton();
        pedir = new javax.swing.JButton();
        encerrar = new javax.swing.JButton();
        deb = new javax.swing.JRadioButton();
        cre = new javax.swing.JRadioButton();
        money = new javax.swing.JRadioButton();
        pix = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BoxCodigo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Telageral.setBackground(new java.awt.Color(255, 204, 51));

        cardapio.setBackground(new java.awt.Color(0, 204, 255));
        cardapio.setText("Cardapio");
        cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardapioActionPerformed(evt);
            }
        });

        pedir.setBackground(new java.awt.Color(102, 255, 102));
        pedir.setText("Realizar pedido");
        pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirActionPerformed(evt);
            }
        });

        encerrar.setBackground(new java.awt.Color(255, 153, 0));
        encerrar.setText("Finalizar Pedido");
        encerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarActionPerformed(evt);
            }
        });

        deb.setBackground(new java.awt.Color(255, 204, 51));
        buttonGroup1.add(deb);
        deb.setText("Débito");

        cre.setBackground(new java.awt.Color(255, 204, 51));
        buttonGroup1.add(cre);
        cre.setText("Crédito");

        money.setBackground(new java.awt.Color(255, 204, 51));
        buttonGroup1.add(money);
        money.setText("Dinheiro");

        pix.setBackground(new java.awt.Color(255, 204, 51));
        buttonGroup1.add(pix);
        pix.setText("Pix");

        jLabel1.setText("Quantidade");

        quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo Produto");

        jLabel3.setText("Pagamento");

        jLabel4.setText("Restaurante Planeta dos Sabores");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BoxCodigo.setBackground(new java.awt.Color(251, 238, 160));
        BoxCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        BoxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TelageralLayout = new javax.swing.GroupLayout(Telageral);
        Telageral.setLayout(TelageralLayout);
        TelageralLayout.setHorizontalGroup(
            TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelageralLayout.createSequentialGroup()
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelageralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(TelageralLayout.createSequentialGroup()
                                .addComponent(cardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pedir)
                                .addGap(35, 35, 35)
                                .addComponent(encerrar))
                            .addGroup(TelageralLayout.createSequentialGroup()
                                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(TelageralLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(TelageralLayout.createSequentialGroup()
                                        .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(money)
                                            .addComponent(pix)
                                            .addComponent(cre)
                                            .addComponent(deb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(quantidade)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BoxCodigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(152, 152, 152))))
                    .addGroup(TelageralLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TelageralLayout.setVerticalGroup(
            TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelageralLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TelageralLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelageralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(money)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cre)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deb)
                    .addComponent(BoxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(TelageralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encerrar)
                    .addComponent(pedir)
                    .addComponent(cardapio))
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Telageral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Telageral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BoxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //System.exit(0);        // TODO add your handling code here:
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });

    }//GEN-LAST:event_jButton1ActionPerformed

    private void quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeActionPerformed

    private void encerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarActionPerformed
        if(pedido.svalor>0){
            JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nQuantidades de itens pedidos= "+pedido.x+"\nO valor total = "+df.format(pedido.svalor)+"\n Forma de Pagamento= "+pedido.formapagar);
            pedido.svalor=0;
            //pedido.temp=pedido.a;
            //pedido= new Escolha();
        }else{
            //JOptionPane.showInputDialog("Houve um erro inesperado.");
            JOptionPane.showMessageDialog(null,"Houve um erro inesperado!\n"+pedido.svalor+"\n");
        }        // TODO add your handling code here:
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
        
    }//GEN-LAST:event_encerrarActionPerformed

    private void pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirActionPerformed
        //pedido.temp=(Integer)BoxCodigo.getSelectedItem();
        pedido.temp=(Integer.parseInt((String) BoxCodigo.getSelectedItem()));
        pedido.a=(pedido.temp-1);
        pedido.qnt=Integer.parseInt(quantidade.getText());
        if(pix.isSelected()){
            pedido.formapagar=pix.getText();
        }else if(deb.isSelected()){
            pedido.formapagar=deb.getText();
        }else if(cre.isSelected()){
            pedido.formapagar=cre.getText();
        }else if(money.isSelected()){
            pedido.formapagar=money.getText();
        }

        if(pedido.a>=0 && pedido.qnt>0 && pedido.formapagar != null){
            pedido.x+=pedido.qnt;
            for(pedido.p=0;pedido.p<pedido.qnt;pedido.p++){

                if(pedido.a>-1 && pedido.a<=19){
                    pedido.svalor+=pedido.precosPorcoes[pedido.a];

                    if(pedido.p==0){
                        JOptionPane.showMessageDialog(null,"Cliente= "+pedido.cliente+"\nMesa= "+pedido.mesa+"\nPedido = "+(pedido.produto[pedido.a])+"\nQuantidade = "+pedido.qnt+"\n Valor por item= "+df.format(pedido.precosPorcoes[pedido.a]));
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, " Codigo invalido");
                }
            }  /*  pedidos.add(pedido);
            pedido.cardapio=pedido.produto[pedido.a];
            pedido.precopro=pedido.precosPorcoes[pedido.a];
            Object[] rowData = {pedido.cardapio, pedido.precopro, pedido.qnt, pedido.formapagar, pedido.svalor};
            modelo.addRow(rowData);
            // modelo.addRow(pedido.cardapio,pedido.precopro,pedido.qnt,pedido.formapagar,pedido.svalor);
            //modelo.addRow(pedido.cardapio,pedido.precopro,pedido.qnt,pedido.formapagar,pedido.svalor);*/

        }
        else if ( pedido.qnt<=0 || pedido.a<=-1){
            JOptionPane.showMessageDialog(null, "Pedido NÃO REALIZADO\n  Por favor preencha corretamente");
        }
        else{
            JOptionPane.showMessageDialog(null, "Pedido NÃO REALIZADO\n Quantidade, Codigo ou Pagamento incorreto!");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_pedirActionPerformed

    private void cardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapioActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        //setVisible(false);  
    }//GEN-LAST:event_cardapioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela2().setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxCodigo;
    private javax.swing.JPanel Telageral;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cardapio;
    private javax.swing.JRadioButton cre;
    private javax.swing.JRadioButton deb;
    private javax.swing.JButton encerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton money;
    private javax.swing.JButton pedir;
    private javax.swing.JRadioButton pix;
    private javax.swing.JTextField quantidade;
    // End of variables declaration//GEN-END:variables
}
